# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from app.proto import edge_pb2 as proto_dot_edge__pb2


class EdgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateBitrate = channel.unary_unary(
                '/Edge/UpdateBitrate',
                request_serializer=proto_dot_edge__pb2.Bitrate.SerializeToString,
                response_deserializer=proto_dot_edge__pb2.IsUpdated.FromString,
                )
        self.NotifyJobDone = channel.unary_unary(
                '/Edge/NotifyJobDone',
                request_serializer=proto_dot_edge__pb2.IsJobDone.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class EdgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateBitrate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyJobDone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EdgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateBitrate': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBitrate,
                    request_deserializer=proto_dot_edge__pb2.Bitrate.FromString,
                    response_serializer=proto_dot_edge__pb2.IsUpdated.SerializeToString,
            ),
            'NotifyJobDone': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyJobDone,
                    request_deserializer=proto_dot_edge__pb2.IsJobDone.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Edge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Edge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateBitrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Edge/UpdateBitrate',
            proto_dot_edge__pb2.Bitrate.SerializeToString,
            proto_dot_edge__pb2.IsUpdated.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyJobDone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Edge/NotifyJobDone',
            proto_dot_edge__pb2.IsJobDone.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
