# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_server.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61pp_server.proto\x1a\x1bgoogle/protobuf/empty.proto\"5\n\x0eResourceChange\x12\x0e\n\x06\x63hange\x18\x01 \x01(\x02\x12\x13\n\x0b\x63\x61n_proceed\x18\x02 \x01(\x08\"\"\n\x0cResourceType\x12\x12\n\nresource_t\x18\x01 \x01(\t\"\xc6\x01\n\x04\x44iff\x12\x12\n\ninfer_diff\x18\x01 \x01(\x02\x12\x14\n\x0clatency_diff\x18\x02 \x01(\x02\x12\x17\n\x0finfer_diff_high\x18\x03 \x01(\x02\x12\x16\n\x0einfer_diff_low\x18\x04 \x01(\x02\x12\x16\n\x0e\x62w_lower_bound\x18\x05 \x01(\x02\x12\x11\n\tis_min_bw\x18\x06 \x01(\x08\x12\x12\n\ncurr_frame\x18\x07 \x01(\r\x12\x0f\n\x07\x63urr_f1\x18\x08 \x01(\x02\x12\x13\n\x0b\x63urr_budget\x18\t \x01(\x02\"\x97\x01\n\x0cNotification\x12\x12\n\nis_succeed\x18\x01 \x01(\x08\x12\x15\n\ractual_amount\x18\x02 \x01(\x02\x12\x12\n\nresource_t\x18\x03 \x01(\t\x12 \n\x18\x63\x61n_clear_profiling_flag\x18\x04 \x01(\x08\x12\x11\n\tis_min_bw\x18\x05 \x01(\x08\x12\x13\n\x0b\x63\x61n_proceed\x18\x06 \x01(\x08\"\x1e\n\nIsNotified\x12\x10\n\x08notified\x18\x01 \x01(\x08\"\x1b\n\tNewTokens\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\x32\xa8\x02\n\x08Pipeline\x12!\n\x07GetDiff\x12\r.ResourceType\x1a\x05.Diff\"\x00\x12\x32\n\x12NotifyReallocation\x12\r.Notification\x1a\x0b.IsNotified\"\x00\x12.\n\x0cStartProfile\x12\x0f.ResourceChange\x1a\x0b.IsNotified\"\x00\x12(\n\x0bRefillToken\x12\n.NewTokens\x1a\x0b.IsNotified\"\x00\x12\x34\n\x0bStartGPUJob\x12\x16.google.protobuf.Empty\x1a\x0b.IsNotified\"\x00\x12\x35\n\x0c\x45ndInference\x12\x16.google.protobuf.Empty\x1a\x0b.IsNotified\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESOURCECHANGE']._serialized_start=49
  _globals['_RESOURCECHANGE']._serialized_end=102
  _globals['_RESOURCETYPE']._serialized_start=104
  _globals['_RESOURCETYPE']._serialized_end=138
  _globals['_DIFF']._serialized_start=141
  _globals['_DIFF']._serialized_end=339
  _globals['_NOTIFICATION']._serialized_start=342
  _globals['_NOTIFICATION']._serialized_end=493
  _globals['_ISNOTIFIED']._serialized_start=495
  _globals['_ISNOTIFIED']._serialized_end=525
  _globals['_NEWTOKENS']._serialized_start=527
  _globals['_NEWTOKENS']._serialized_end=554
  _globals['_PIPELINE']._serialized_start=557
  _globals['_PIPELINE']._serialized_end=853
# @@protoc_insertion_point(module_scope)
