# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: concierge.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63oncierge.proto\x1a\x1bgoogle/protobuf/empty.proto\"{\n\x07\x41ppInfo\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\x12\x12\n\nserver_uri\x18\x02 \x01(\t\x12\x12\n\nclient_uri\x18\x03 \x01(\t\x12\x13\n\x0bserver_port\x18\x04 \x01(\r\x12\x10\n\x08is_faked\x18\x05 \x01(\x08\x12\x0b\n\x03pid\x18\x06 \x01(\x04\";\n\x0c\x42\x61selineInfo\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\x12\x15\n\tf1_scores\x18\x02 \x03(\x01\x42\x02\x10\x01\"<\n\x03PID\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\r\x12\x12\n\nresource_t\x18\x03 \x01(\t\"F\n\nResRequest\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\t\x12\x12\n\nresource_t\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\"\x1c\n\x06Status\x12\x12\n\nis_succeed\x18\x01 \x01(\x08\x32\xc0\x02\n\tConcierge\x12!\n\nCheckinApp\x12\x08.AppInfo\x1a\x07.Status\"\x00\x12)\n\x0fRequestResource\x12\x0b.ResRequest\x1a\x07.Status\"\x00\x12!\n\x0eReadyToProfile\x12\x04.PID\x1a\x07.Status\"\x00\x12\x1e\n\x0b\x44oneProfile\x12\x04.PID\x1a\x07.Status\"\x00\x12#\n\x0cSubmitGPUJob\x12\x08.AppInfo\x1a\x07.Status\"\x00\x12/\n\nDoneGPUJob\x12\x16.google.protobuf.Empty\x1a\x07.Status\"\x00\x12$\n\rDoneInference\x12\x08.AppInfo\x1a\x07.Status\"\x00\x12&\n\nBaselineBW\x12\r.BaselineInfo\x1a\x07.Status\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'concierge_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BASELINEINFO'].fields_by_name['f1_scores']._options = None
  _globals['_BASELINEINFO'].fields_by_name['f1_scores']._serialized_options = b'\020\001'
  _globals['_APPINFO']._serialized_start=48
  _globals['_APPINFO']._serialized_end=171
  _globals['_BASELINEINFO']._serialized_start=173
  _globals['_BASELINEINFO']._serialized_end=232
  _globals['_PID']._serialized_start=234
  _globals['_PID']._serialized_end=294
  _globals['_RESREQUEST']._serialized_start=296
  _globals['_RESREQUEST']._serialized_end=366
  _globals['_STATUS']._serialized_start=368
  _globals['_STATUS']._serialized_end=396
  _globals['_CONCIERGE']._serialized_start=399
  _globals['_CONCIERGE']._serialized_end=719
# @@protoc_insertion_point(module_scope)
