# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api.proto.concierge_pb2 as concierge__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ConciergeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckinApp = channel.unary_unary(
                '/Concierge/CheckinApp',
                request_serializer=concierge__pb2.AppInfo.SerializeToString,
                response_deserializer=concierge__pb2.Status.FromString,
                )
        self.RequestResource = channel.unary_unary(
                '/Concierge/RequestResource',
                request_serializer=concierge__pb2.ResRequest.SerializeToString,
                response_deserializer=concierge__pb2.Status.FromString,
                )
        self.ReadyToProfile = channel.unary_unary(
                '/Concierge/ReadyToProfile',
                request_serializer=concierge__pb2.PID.SerializeToString,
                response_deserializer=concierge__pb2.Status.FromString,
                )
        self.DoneProfile = channel.unary_unary(
                '/Concierge/DoneProfile',
                request_serializer=concierge__pb2.PID.SerializeToString,
                response_deserializer=concierge__pb2.Status.FromString,
                )
        self.SubmitGPUJob = channel.unary_unary(
                '/Concierge/SubmitGPUJob',
                request_serializer=concierge__pb2.AppInfo.SerializeToString,
                response_deserializer=concierge__pb2.Status.FromString,
                )
        self.DoneGPUJob = channel.unary_unary(
                '/Concierge/DoneGPUJob',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=concierge__pb2.Status.FromString,
                )
        self.DoneInference = channel.unary_unary(
                '/Concierge/DoneInference',
                request_serializer=concierge__pb2.AppInfo.SerializeToString,
                response_deserializer=concierge__pb2.Status.FromString,
                )
        self.BaselineBW = channel.unary_unary(
                '/Concierge/BaselineBW',
                request_serializer=concierge__pb2.BaselineInfo.SerializeToString,
                response_deserializer=concierge__pb2.Status.FromString,
                )


class ConciergeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckinApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadyToProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoneProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitGPUJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoneGPUJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DoneInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BaselineBW(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConciergeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckinApp': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckinApp,
                    request_deserializer=concierge__pb2.AppInfo.FromString,
                    response_serializer=concierge__pb2.Status.SerializeToString,
            ),
            'RequestResource': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestResource,
                    request_deserializer=concierge__pb2.ResRequest.FromString,
                    response_serializer=concierge__pb2.Status.SerializeToString,
            ),
            'ReadyToProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadyToProfile,
                    request_deserializer=concierge__pb2.PID.FromString,
                    response_serializer=concierge__pb2.Status.SerializeToString,
            ),
            'DoneProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.DoneProfile,
                    request_deserializer=concierge__pb2.PID.FromString,
                    response_serializer=concierge__pb2.Status.SerializeToString,
            ),
            'SubmitGPUJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitGPUJob,
                    request_deserializer=concierge__pb2.AppInfo.FromString,
                    response_serializer=concierge__pb2.Status.SerializeToString,
            ),
            'DoneGPUJob': grpc.unary_unary_rpc_method_handler(
                    servicer.DoneGPUJob,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=concierge__pb2.Status.SerializeToString,
            ),
            'DoneInference': grpc.unary_unary_rpc_method_handler(
                    servicer.DoneInference,
                    request_deserializer=concierge__pb2.AppInfo.FromString,
                    response_serializer=concierge__pb2.Status.SerializeToString,
            ),
            'BaselineBW': grpc.unary_unary_rpc_method_handler(
                    servicer.BaselineBW,
                    request_deserializer=concierge__pb2.BaselineInfo.FromString,
                    response_serializer=concierge__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Concierge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Concierge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckinApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Concierge/CheckinApp',
            concierge__pb2.AppInfo.SerializeToString,
            concierge__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Concierge/RequestResource',
            concierge__pb2.ResRequest.SerializeToString,
            concierge__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReadyToProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Concierge/ReadyToProfile',
            concierge__pb2.PID.SerializeToString,
            concierge__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DoneProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Concierge/DoneProfile',
            concierge__pb2.PID.SerializeToString,
            concierge__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitGPUJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Concierge/SubmitGPUJob',
            concierge__pb2.AppInfo.SerializeToString,
            concierge__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DoneGPUJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Concierge/DoneGPUJob',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            concierge__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DoneInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Concierge/DoneInference',
            concierge__pb2.AppInfo.SerializeToString,
            concierge__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BaselineBW(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Concierge/BaselineBW',
            concierge__pb2.BaselineInfo.SerializeToString,
            concierge__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
