name: dds
channels:
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - flask
  - munch
  - networkx
  - pyyaml
  - requests
  - pip
  - pip:
    - opencv-contrib-python
    - grpcio
    - google-api-core
 

